// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaWorld.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NinjaWorld.Infrastructure.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    [Migration("20240527073944_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NinjaWorld.Domain.Entities.Ninja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("Village")
                        .HasColumnType("integer")
                        .HasColumnName("village");

                    b.HasKey("Id")
                        .HasName("pk_ninja");

                    b.ToTable("ninja", (string)null);
                });

            modelBuilder.Entity("NinjaWorld.Domain.Entities.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("NinjaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ninja_id");

                    b.Property<int>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.HasKey("Id")
                        .HasName("pk_tool");

                    b.HasIndex("NinjaId")
                        .HasDatabaseName("ix_tool_ninja_id");

                    b.ToTable("tool", (string)null);
                });

            modelBuilder.Entity("NinjaWorld.Domain.Entities.Tool", b =>
                {
                    b.HasOne("NinjaWorld.Domain.Entities.Ninja", null)
                        .WithMany("Tools")
                        .HasForeignKey("NinjaId")
                        .HasConstraintName("fk_tool_ninja_ninja_id");
                });

            modelBuilder.Entity("NinjaWorld.Domain.Entities.Ninja", b =>
                {
                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
